-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
-- Autocmds for Java JDTLS
-- Set up LSP capabilities
-- local capabilities = require("blink-cmp").get_lsp_capabilities({}, true)
--
-- -- Autocmd for Java files
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "java" },
--   callback = function()
--     local jdtls_config = require("config.lsp.jdtls")
--     jdtls_config.capabilities = capabilities
--
--     vim.lsp.config("jdtls", jdtls_config)
--     vim.lsp.enable("jdtls")
--   end,
-- })
--
-- -- Autocmd for HTML files
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "html", "htm" },
--   callback = function()
--     local html_config = require("config.lsp.html")
--     html_config.capabilities = capabilities
--
--     vim.lsp.config("html", html_config)
--     vim.lsp.enable("html")
--   end,
-- })
--
-- -- Autocmd for CSS files
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "css", "scss", "less" },
--   callback = function()
--     local css_config = require("config.lsp.cssls")
--     css_config.capabilities = capabilities
--
--     vim.lsp.config("css", css_config)
--     vim.lsp.enable("css")
--   end,
-- })
--
-- --Autocmd for Tailwind
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "html", "css", "scss", "js", "jsx" },
--   callback = function()
--     local tailwind_config = require("config.lsp.twind")
--     tailwind_config.capabilities = capabilities
--
--     vim.lsp.config("twind", tailwind_config)
--     vim.lsp.enable("twind")
--   end,
-- })
